version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-password}
      - MONGO_INITDB_DATABASE=${MONGO_INITDB_DATABASE:-todo-app}
    networks:
      - mongo_network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh --quiet
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  app:
    build:
      context: ../
      dockerfile: Dockerfile
    container_name: todo-app
    restart: unless-stopped
    command:
      - node dist/server.js
    entrypoint: [ "node", "dist/server.js" ]
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://${MONGO_ROOT_USERNAME:-admin}:${MONGO_ROOT_PASSWORD:-password}@mongodb:27017/${MONGO_INITDB_DATABASE:-todo-app}?authSource=admin
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - mongo_network

networks:
  mongo_network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local